title: Justin Reed # your name (or website title) here
logo: "/images/profilepic.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  <a href="https://www.linkedin.com/in/justinthreed/">LinkedIn</a> 
  <br>
  <a href="pdf/Resume - Justin Reed.pdf" class="btn btn--info">Resume</a>  
  <br>
  <a href="https://github.com/justinreed23">GitHub</a> 
  
theme: jekyll-theme-minimal